
from django.contrib import admin
from django.urls import path
from bMSapp import views
urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('', views.landing_page, name='landing_page'),
    path('admin/', admin.site.urls),
    path('whiteboard/', views.whiteboard, name='whiteboard'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('player/', views.player_after_login, name='player_after_login'),
    path('coach/', views.coach_after_login, name='coach_after_login'),
    path('manager/', views.manager_after_login, name='manager_after_login'),
    path('edit_player_profile/<str:username>/',
         views.edit_player_profile, name='edit_player_profile'),
    path('edit_coach_profile/<str:username>/',
         views.edit_coach_profile, name='edit_coach_profile'),
    path('delete_player_profile/<str:username>/',
         views.delete_player_profile, name='delete_player_profile'),
    path('delete_coach_profile/<str:username>/',
         views.delete_coach_profile, name='delete_coach_profile'),
    path('activate/<uidb64>/<token>', views.verify_user, name='activate'),
    path('advance_month/', views.advance_month, name='advance_month'),
    path('announcements/', views.announcements, name='announcements'),
    path('announcements_player/', views.announcements_player,
         name='announcements_player'),
    path('basketball_whiteboard/', views.basketball_whiteboard,
         name='basketball_whiteboard'),
    path('view_images/', views.view_images, name='view_images'),
    path('save_canvas_image/', views.save_canvas_image, name='save_canvas_image'),
    path('delete_canvas_image/<int:image_id>/',
         views.delete_canvas_image, name='delete_canvas_image'),
    path('authenticate/', views.authenticate_google, name='authenticate'),
    path('calendar/', views.calendar, name='calendar'),
    path('playbook/', views.playbook, name='playbook'),
    path('delete_event/<str:event_id>/',
         views.delete_event, name='delete_event'),
    path('pricing/', views.pricing, name='pricing'),
    path('contact/', views.contact, name='contact'),
    path('calendar_player', views.calendar_player, name='calendar_player'),
    path('delete_announcement/<int:announcement_id>/',
         views.delete_announcement, name='delete_announcement'),
     

]
