# Generated by Django 4.2 on 2023-04-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bMSapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=50),
        ),
    ]
