# Generated by Django 4.1.2 on 2023-04-19 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bMSapp", "0002_alter_player_position"),
    ]

    operations = [
        migrations.RemoveField(model_name="coach", name="team",),
        migrations.RemoveField(model_name="manager", name="team",),
        migrations.RemoveField(model_name="player", name="team",),
        migrations.RemoveField(model_name="profile", name="email",),
        migrations.RemoveField(model_name="profile", name="firstname",),
        migrations.RemoveField(model_name="profile", name="is_coach",),
        migrations.RemoveField(model_name="profile", name="is_manager",),
        migrations.RemoveField(model_name="profile", name="is_player",),
        migrations.RemoveField(model_name="profile", name="lastname",),
        migrations.RemoveField(model_name="profile", name="username",),
    ]
