# Generated by Django 4.1.2 on 2023-04-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bMSapp", "0003_remove_coach_team_remove_manager_team_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CanvasImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_data", models.TextField()),
            ],
        ),
    ]
