# Generated by Django 4.1.2 on 2023-04-25 16:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("bMSapp", "0004_canvasimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="canvasimage",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="canvasimage",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
        ),
        migrations.AlterField(
            model_name="canvasimage", name="image_data", field=models.BinaryField(),
        ),
    ]
